name: Build Intel Shared Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Intel Fortran Compiler (ifx)
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: intel
          version: '2024.1'

      - name: Build Shared Library
        shell: bash
        run: |
          # Download ONLY the bmi.f90 file from the master branch
          curl -O https://raw.githubusercontent.com/csdms/bmi-fortran/master/bmi.f90
          INCLUDE_DIR="-Iheat"
          SOURCE_FILE="bmi.f90 bmi_heat/bmi_heat_shared.f90"
          MODEL_FILE="heat/heat.f90"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Building DLL for Windows..."
            $FC //LD //fpp $INCLUDE_DIR -o libbmi_heat.dll $MODEL_FILE $SOURCE_FILE
          else
            echo "Building Shared Object for Linux..."
            $FC -shared -fPIC -fpp $INCLUDE_DIR -o libbmi_heat.so $MODEL_FILE $SOURCE_FILE
          fi

      - name: Harvest Intel Runtime Libraries
        shell: bash
        run: |
          echo "Creating a folder to hold the runtime libraries..."
          mkdir -p intel_redist

          echo check the path:
          echo "CMPLR_ROOT is: $CMPLR_ROOT"
          ls "$CMPLR_ROOT/lib/" | grep -E "libifcore|libimf|libsvml|libintlc"
                  
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            REDIST="$CMPLR_ROOT/bin"
            cp "$REDIST/libifcoremd.dll" ./intel_redist/
            cp "$REDIST/libmmd.dll" ./intel_redist/
            cp "$REDIST/svml_dispmd.dll" ./intel_redist/
            cp "$REDIST/libiomp5md.dll" ./intel_redist/
          else
            REDIST="$CMPLR_ROOT/lib"
            cp "$REDIST/libifcore.so.5" ./intel_redist/
            cp "$REDIST/libimf.so" ./intel_redist/
            cp "$REDIST/libsvml.so" ./intel_redist/
            cp "$REDIST/libintlc.so.5" ./intel_redist/
          fi
          
      - name: Upload Compiled Libraries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-library-${{ matrix.os }}
          path: |
            *.so
            *.dll
            *.lib
            intel_redist/
          if-no-files-found: error
          
